#!/usr/bin/env python3
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
DATA=ROOT/'reports'/'v2'/'data.json'
HTML=ROOT/'reports'/'v2'/'index.html'
DECISION_HTML=ROOT/'reports'/'decision_os'/'index.html'


def main():
    d=json.loads(DATA.read_text(encoding='utf-8'))
    data=json.dumps(d,ensure_ascii=False).replace('</','<\\/')
    html='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><title>E-commerce Decision OS</title><style>
:root{--bg:#f3f6fb;--card:#fff;--text:#111827;--muted:#64748b;--line:#e2e8f0;--blue:#0874e8;--red:#dc2626;--amber:#d97706;--green:#059669;--navy:#111827}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,'Noto Sans KR',system-ui,sans-serif}main{max-width:1440px;margin:auto;padding:18px}.hero{display:flex;justify-content:space-between;align-items:flex-end;gap:12px;margin-bottom:12px}.hero h1{margin:3px 0;font-size:29px}.eyebrow{font-size:10px;letter-spacing:.16em;color:var(--blue);font-weight:900}.sub{font-size:11px;color:var(--muted);line-height:1.45}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:10px}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:15px;box-shadow:0 6px 22px rgba(15,23,42,.045);min-width:0}.s12{grid-column:span 12}.s8{grid-column:span 8}.s6{grid-column:span 6}.s4{grid-column:span 4}h2{font-size:15px;margin:0 0 10px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.kpi{background:var(--bg);border-radius:11px;padding:11px;min-width:0}.kpi b{display:block;font-size:18px;overflow-wrap:anywhere}.command{background:linear-gradient(135deg,#111827,#1e3a5f);color:#fff}.command .sub{color:#cbd5e1}.command-grid{display:grid;grid-template-columns:1.5fr repeat(3,1fr);gap:8px}.command-box{padding:13px;border-radius:12px;background:rgba(255,255,255,.08)}.command-box strong{display:block;font-size:18px;margin-top:4px}.row{padding:10px 0;border-bottom:1px solid var(--line)}.row:last-child{border-bottom:0}.level{font-size:9px;font-weight:900}.critical{color:var(--red)}.warning{color:var(--amber)}.healthy,.live{color:var(--green)}.waiting{color:var(--muted)}.pill{display:inline-flex;padding:4px 7px;border-radius:999px;background:#eef2f7;font-size:9px;font-weight:800;margin-right:4px}.incident{display:grid;grid-template-columns:72px 1fr 130px;gap:9px;align-items:start}.incident .risk{text-align:right}.bar{height:7px;background:#e5e7eb;border-radius:999px;overflow:hidden;margin-top:5px}.bar span{display:block;height:100%;background:var(--blue)}.connections,.features,.experiments,.products{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.mini{background:var(--bg);border-radius:11px;padding:10px;min-width:0}.mini b{overflow-wrap:anywhere}.error{padding:12px;border:1px solid #fecaca;background:#fef2f2;color:#991b1b;border-radius:10px}.link{color:var(--blue);text-decoration:none;font-size:11px;font-weight:800}.empty{padding:18px;text-align:center;color:var(--muted);font-size:12px}.table-head{font-size:9px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.metric{font-size:24px;font-weight:900}.nowrap{white-space:nowrap}.progress{height:8px;background:#e5e7eb;border-radius:999px;overflow:hidden}.progress span{height:100%;display:block;background:var(--blue)}
@media(max-width:760px){main{padding:10px 8px 78px}.hero h1{font-size:21px}.hero{align-items:flex-start}.s8,.s6,.s4{grid-column:span 12}.card{padding:12px;border-radius:13px}.kpis{grid-template-columns:repeat(2,1fr)}.command-grid{grid-template-columns:1fr 1fr}.command-grid .command-box:first-child{grid-column:span 2}.incident{grid-template-columns:56px 1fr}.incident .risk{grid-column:2;text-align:left}.connections,.features,.experiments,.products{grid-template-columns:1fr}.kpi b{font-size:16px}h2{font-size:14px}}
</style></head><body><main><header class="hero"><div><div class="eyebrow">E-COMMERCE DECISION OPERATING SYSTEM</div><h1>Marketing Hub v2</h1><div class="sub" id="updated"></div></div><a class="link" href="../realtime_alerts/index.html">Realtime 상세 →</a></header><section class="grid">
<article class="card s12 command"><h2>Executive Command Center</h2><div id="command"></div></article>
<article class="card s12"><h2>오늘의 핵심 KPI</h2><div id="kpis"></div></article>
<article class="card s8"><h2>Incident Center · 중복 Alert 통합</h2><div id="incidents"></div></article>
<article class="card s4"><h2>Revenue at Risk</h2><div id="risk"></div></article>
<article class="card s6"><h2>Root Cause Inference</h2><div id="causes"></div></article>
<article class="card s6"><h2>Measurement vs Business</h2><div id="diagnosis"></div></article>
<article class="card s6"><h2>Multi-baseline Ensemble</h2><div id="baseline"></div></article>
<article class="card s6"><h2>Realtime BigQuery Monitoring</h2><div id="realtime"></div></article>
<article class="card s12"><h2>Decision Actions & Experiment Engine</h2><div id="experiments"></div></article>
<article class="card s6"><h2>Product Context · 가격/재고/PDP</h2><div id="products"></div></article>
<article class="card s6"><h2>Profitability Intelligence</h2><div id="profit"></div></article>
<article class="card s12"><h2>Feature Readiness · 10개 고도화</h2><div id="features"></div></article>
<article class="card s12"><h2>Data Connection Registry</h2><div id="connections"></div></article>
<article class="card s12"><h2>Alert Center</h2><div id="alerts"></div></article>
</section></main><script>
const D=__DATA__;const O=(D&&D.decision_os)||{};
const el=id=>document.getElementById(id);const list=x=>Array.isArray(x)?x:[];const obj=x=>x&&typeof x==='object'?x:{};const esc=x=>String(x??'-').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const nf=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('ko-KR',{notation:'compact',maximumFractionDigits:1}).format(Number(n)):'-';const won=n=>nf(n)+(nf(n)==='-'?'':'원');const pct=n=>Number.isFinite(Number(n))?((Math.abs(Number(n))<=1?Number(n)*100:Number(n)).toFixed(1)+'%'):'-';
function render(id,fn){try{el(id).innerHTML=fn()}catch(e){el(id).innerHTML='<div class="error">표시 오류: '+esc(e.message)+'</div>';console.error(id,e)}}
el('updated').textContent=(D.generated_at||O.generated_at||'-')+' · Decision OS '+(O.version||'연결 대기');
render('command',()=>{const c=obj(O.command_center);return '<div class="command-grid"><div class="command-box"><div class="sub">NOW</div><strong>'+esc(c.headline||'Decision OS 데이터 연결 대기')+'</strong><div class="sub">관측 '+esc(c.observed_hour||'-')+'</div></div>'+[['Critical Incident',nf(c.critical_incidents)],['오늘 위험매출',won(c.revenue_at_risk_today)],['Data Trust',nf(c.data_trust_score)+'점']].map(x=>'<div class="command-box"><div class="sub">'+x[0]+'</div><strong>'+x[1]+'</strong></div>').join('')+'<div class="command-box" style="grid-column:1/-1"><div class="sub">TOP RECOMMENDED ACTION</div><strong>'+esc(c.top_recommended_action||'현재 추천 액션 없음')+'</strong></div></div>'});
render('kpis',()=>{const m=obj(D.metrics);return '<div class="kpis">'+[['매출',won(m.revenue)],['주문',nf(m.orders)],['세션',nf(m.sessions)],['CVR',pct(m.cvr)],['사용자',nf(m.users)],['AOV',won(m.aov)],['가입',nf(m.signups)],['Alert',nf((D.alerts||[]).length)]].map(x=>'<div class="kpi"><span class="sub">'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')+'</div>'});
render('incidents',()=>list(O.incidents).map(x=>'<div class="row incident"><div><span class="level '+esc(x.level)+'">'+esc(x.level).toUpperCase()+'</span><br><span class="pill">'+esc(x.status)+'</span></div><div><b>'+esc(x.incident_id)+' · '+esc(x.title)+'</b><div class="sub">'+esc(x.dimension_type)+' / '+esc(x.dimension_value)+' · Alert '+nf(x.alert_count)+'건<br>최초 '+esc(x.first_seen)+' · 최근 '+esc(x.last_seen)+' · 담당 '+esc(x.owner)+'</div></div><div class="risk"><b>'+won(obj(x.revenue_at_risk).today)+'</b><div class="sub">오늘 위험매출</div></div></div>').join('')||'<div class="empty">현재 활성 Incident가 없습니다.</div>');
render('risk',()=>{const r=obj(O.revenue_risk);return '<div class="metric">'+won(r.today)+'</div><div class="sub">오늘 예상 손실</div><div class="row"><b>7일 지속</b><span style="float:right">'+won(r.seven_day)+'</span></div><div class="row"><b>회복 가능</b><span style="float:right">'+won(r.recoverable)+'</span></div>'});
render('causes',()=>list(O.root_cause_inference).slice(0,10).map(x=>'<div class="row"><b>'+esc(x.dimension_value)+' · '+esc(x.cause)+'</b><div class="sub">신뢰도 '+nf(x.confidence)+'% · '+esc(x.diagnosis)+'<br>'+list(x.evidence).map(esc).join(' · ')+'</div><div class="bar"><span style="width:'+Math.min(100,Number(x.confidence)||0)+'%"></span></div></div>').join('')||'<div class="empty">원인 추론 대상 Alert가 없습니다.</div>');
render('diagnosis',()=>{const x=obj(O.measurement_diagnosis);return '<div class="kpis"><div class="kpi"><span class="sub">측정 오류 가능성</span><b>'+nf(x.measurement_probability)+'%</b></div><div class="kpi"><span class="sub">실제 성과 문제</span><b>'+nf(x.business_probability)+'%</b></div></div><div class="row"><span class="pill '+esc(x.status)+'">'+esc(x.status).toUpperCase()+'</span><div class="sub">'+list(x.evidence).map(esc).join('<br>')+'</div></div>'});
render('baseline',()=>{const b=obj(O.baseline_ensemble);return '<p><span class="pill '+esc(b.status)+'">'+esc(b.status).toUpperCase()+'</span> 기준선 신뢰도 <b>'+esc(b.confidence)+'</b></p>'+list(b.methods).map(x=>'<div class="row"><b>'+esc(x.name)+'</b><span style="float:right">'+esc(x.status)+' · '+pct(x.weight)+'</span></div>').join('')});
render('realtime',()=>{const r=obj(D.realtime_alerts);return r.status?'<div class="kpis">'+[['상태',String(r.status).toUpperCase()],['알림',nf(r.alert_count)],['Critical',nf(r.critical_count)],['관측',esc(r.observed_hour)]].map(x=>'<div class="kpi"><span class="sub">'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')+'</div>':'<div class="empty">실시간 감시 데이터가 없습니다.</div>'});
render('experiments',()=>'<div class="experiments">'+list(O.experiments).map(x=>'<div class="mini"><span class="pill">'+esc(x.effort)+'</span><b>'+esc(x.title)+'</b><div class="sub">Primary '+esc(x.primary_metric)+'<br>기대 '+esc(x.expected_lift)+' · '+esc(x.duration)+'<br>필요 표본 '+nf(x.minimum_sample)+' · 예상 '+won(x.estimated_revenue)+'</div></div>').join('')+'</div>'||'<div class="empty">추천 실험이 없습니다.</div>');
render('products',()=>'<div class="products">'+list(O.product_context).slice(0,12).map(x=>'<div class="mini"><b>'+esc(x.product_name)+'</b><div class="sub">'+esc(x.product_code)+'<br>기회점수 '+nf(x.opportunity_score)+' · 세션 '+nf(x.sessions)+' · CVR '+pct(x.cvr)+'<br>가격 '+won(x.price)+' · 재고 '+esc(x.stock)+' · <span class="'+esc(x.inventory_status)+'">'+esc(x.inventory_status)+'</span></div></div>').join('')+'</div>'||'<div class="empty">상품 데이터가 없습니다.</div>');
render('profit',()=>{const p=obj(O.profitability);return '<p><span class="pill '+esc(p.status)+'">'+esc(p.status).toUpperCase()+'</span></p><div class="kpis">'+[['광고비',won(p.spend)],['광고매출',won(p.revenue)],['ROAS',pct(p.roas)],['기여 ROAS',pct(p.contribution_roas)]].map(x=>'<div class="kpi"><span class="sub">'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')+'</div><p class="sub">마진 데이터가 연결되면 기여이익 기준으로 자동 전환됩니다.</p>'});
render('features',()=>'<div class="features">'+list(O.feature_status).map(x=>'<div class="mini"><b>'+esc(x.label)+'</b><span style="float:right" class="'+esc(x.status)+'">'+esc(x.status).toUpperCase()+'</span><div class="sub">'+esc(x.key)+'</div></div>').join('')+'</div>');
render('connections',()=>'<div class="connections">'+list(O.connections).map(x=>'<div class="mini"><b>'+esc(x.name)+'</b><span style="float:right" class="'+esc(x.status)+'">'+esc(x.status).toUpperCase()+'</span><div class="sub">'+esc(x.path)+'<br>필수: '+(list(x.required).map(esc).join(', ')||'없음')+'</div></div>').join('')+'</div>');
render('alerts',()=>list(D.alerts).slice(0,50).map(x=>'<div class="row"><span class="level '+esc(x.level)+'">'+esc(x.level).toUpperCase()+'</span> · <b>'+esc(x.title)+'</b><div class="sub">'+esc(x.impact)+'<br>'+esc(x.cause)+'<br>Action: '+esc(x.action)+'</div></div>').join('')||'<div class="empty">활성 Alert가 없습니다.</div>');
</script></body></html>'''.replace('__DATA__',data)
    HTML.write_text(html,encoding='utf-8')
    DECISION_HTML.parent.mkdir(parents=True,exist_ok=True)
    DECISION_HTML.write_text(html,encoding='utf-8')
    print('[OK] Decision OS safe renderer completed')

if __name__=='__main__': main()
