#!/usr/bin/env python3
"""Render the PDP drop-off priority dashboard from the latest GA4 product data."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "reports" / "pdp_opportunity" / "data.json"
OUT = ROOT / "reports" / "pdp_opportunity" / "index.html"


def main() -> int:
    if not DATA.exists():
        raise SystemExit(f"[ERROR] Missing PDP data: {DATA}")
    payload = json.loads(DATA.read_text(encoding="utf-8"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(TEMPLATE, encoding="utf-8")
    print(f"[OK] rendered {OUT} with {len(payload.get('products', []))} products")
    return 0


TEMPLATE = r'''<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><title>PDP 이탈 우선순위 | CSK E-COMM</title>
<script src="https://cdn.tailwindcss.com"></script><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
<style>
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@500;700;800&display=swap');@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');
:root{--brand:#0d3b8e;--ink:#0f172a;--muted:#64748b;--glass:rgba(255,255,255,.72);--line:rgba(255,255,255,.86)}*{box-sizing:border-box}html,body{min-height:100%}body{margin:0;color:var(--ink);font-family:Pretendard,"Plus Jakarta Sans",sans-serif;background:radial-gradient(circle at 8% 8%,rgba(37,99,235,.14),transparent 27%),radial-gradient(circle at 92% 2%,rgba(14,165,233,.12),transparent 25%),linear-gradient(180deg,#f6f8fc,#e7eff9)}
.shell{max-width:1720px;margin:auto;padding:28px}.glass{background:var(--glass);backdrop-filter:blur(20px);border:1px solid var(--line);box-shadow:0 24px 70px rgba(13,59,142,.1)}.hero{border-radius:34px;padding:28px;background:linear-gradient(135deg,rgba(255,255,255,.92),rgba(239,246,255,.68))}.eyebrow{font-size:10px;letter-spacing:.25em;font-weight:900;text-transform:uppercase;color:#2563eb}.muted{color:var(--muted)}.pill{display:inline-flex;align-items:center;gap:7px;padding:9px 12px;border-radius:999px;background:rgba(255,255,255,.82);border:1px solid rgba(13,59,142,.08);font-size:12px;font-weight:900;color:#475569}
.kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:16px 0}.kpi{border-radius:24px;padding:18px}.kpi-value{font-size:28px;font-weight:900;letter-spacing:-.04em;margin-top:5px}.panel{border-radius:30px;padding:22px}.controls{display:grid;grid-template-columns:1.5fr repeat(3,minmax(150px,.6fr));gap:10px;margin-bottom:16px}input,select{width:100%;padding:12px 14px;border:1px solid rgba(255,255,255,.95);border-radius:16px;background:rgba(255,255,255,.82);font-weight:800;color:#334155;outline:none}input:focus,select:focus{box-shadow:0 0 0 5px rgba(37,99,235,.09);border-color:rgba(37,99,235,.22)}
.table-wrap{overflow:auto;border-radius:22px;background:rgba(255,255,255,.58)}table{width:100%;border-collapse:collapse;min-width:1050px}th{position:sticky;top:0;z-index:1;background:#eef4fc;color:#64748b;font-size:10px;letter-spacing:.1em;text-transform:uppercase;text-align:right;padding:13px 12px}th:nth-child(1),th:nth-child(2){text-align:left}td{padding:14px 12px;border-top:1px solid rgba(148,163,184,.16);text-align:right;font-size:13px;font-weight:800}td:nth-child(1),td:nth-child(2){text-align:left}tbody tr:hover{background:rgba(255,255,255,.8)}.rank{width:36px;height:36px;display:grid;place-items:center;border-radius:12px;background:#eaf2ff;color:var(--brand);font-weight:900}.code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:#475569;font-size:12px}.bar{height:6px;border-radius:99px;background:#e2e8f0;overflow:hidden;margin-top:7px}.bar>i{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,#fb923c,#dc2626)}.priority{display:inline-flex;min-width:48px;justify-content:center;padding:7px 9px;border-radius:11px;background:#eaf2ff;color:#1d4ed8}.critical{background:#fee2e2;color:#b91c1c}.high{background:#ffedd5;color:#c2410c}.empty{padding:46px;text-align:center;color:#64748b;font-weight:800}.note{font-size:12px;line-height:1.65;color:#64748b;margin-top:14px}
@media(max-width:850px){.shell{padding:10px}.hero{padding:20px;border-radius:24px}.hero h1{font-size:26px!important}.kpis{grid-template-columns:repeat(2,1fr);gap:7px}.kpi{padding:13px;border-radius:18px}.kpi-value{font-size:20px}.panel{padding:10px;border-radius:22px}.controls{grid-template-columns:1fr 1fr}.controls input{grid-column:1/-1}}
</style></head><body><main class="shell">
<header class="hero glass"><div class="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div class="eyebrow mb-3">Performance Analysis · PDP</div><h1 class="text-4xl font-black tracking-tight">PDP 이탈 우선순위</h1><p class="muted mt-3 text-sm font-bold">이탈률이 높은 상품 중 매출 또는 조회 영향도가 큰 상품부터 개선 순서를 확인합니다.</p></div><div class="flex flex-wrap gap-2"><span class="pill"><i class="fa-regular fa-calendar"></i><span id="period">-</span></span><span class="pill"><i class="fa-solid fa-rotate"></i><span id="updated">-</span></span></div></div></header>
<section class="kpis" id="kpis"></section><section class="panel glass"><div class="flex flex-col gap-3 md:flex-row md:items-end md:justify-between mb-5"><div><div class="eyebrow mb-2">Priority List</div><h2 class="text-2xl font-black">개선 대상 상품코드</h2></div><span class="pill" id="resultCount">0개 상품</span></div>
<div class="controls"><input id="search" aria-label="상품 검색" placeholder="상품명 또는 상품코드 검색"><select id="dropFilter" aria-label="최소 이탈률"><option value="70">이탈률 70% 이상</option><option value="80">이탈률 80% 이상</option><option value="90">이탈률 90% 이상</option><option value="0">전체 상품</option></select><select id="volumeFilter" aria-label="최소 조회수"><option value="10">최소 조회 10</option><option value="30">최소 조회 30</option><option value="50">최소 조회 50</option><option value="100">최소 조회 100</option></select><select id="sort" aria-label="정렬"><option value="priority">우선순위: 매출·조회 영향도</option><option value="revenue">매출 높은 순</option><option value="views">조회 높은 순</option><option value="drop">이탈률 높은 순</option><option value="cvr">구매전환 낮은 순</option></select></div>
<div class="table-wrap"><table><thead><tr><th>순위</th><th>상품</th><th>우선순위</th><th>이탈률</th><th>View</th><th>장바구니</th><th>구매</th><th>CVR</th><th>매출</th></tr></thead><tbody id="rows"></tbody></table><div id="empty" class="empty hidden">조건에 맞는 상품이 없습니다.</div></div><p class="note"><b>우선순위 기준:</b> PDP 이탈률(1 − 장바구니 세션 ÷ PDP 조회 세션)이 높은 상품을 대상으로, 매출 또는 View 중 더 큰 영향도를 우선 반영합니다. 매출·View 영향도 80% · 이탈률 20%의 백분위 점수이며, 매출과 View 중 하나가 상위권이면 우선순위가 올라갑니다.</p></section></main>
<script>
let DATA={},ALL=[];const num=v=>Number(v)||0,fmt=v=>new Intl.NumberFormat('ko-KR').format(Math.round(num(v))),won=v=>new Intl.NumberFormat('ko-KR',{notation:'compact',maximumFractionDigits:1}).format(num(v))+'원',pct=v=>num(v).toFixed(1)+'%';const percentile=(arr,v)=>{const a=arr.map(num).sort((x,y)=>x-y);if(!a.length)return 0;let n=0;while(n<a.length&&a[n]<=num(v))n++;return n/a.length};function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const q=search.value.trim().toLowerCase(),minDrop=num(dropFilter.value),minViews=num(volumeFilter.value),mode=sort.value;let list=ALL.filter(x=>num(x.pdp_abandonment_rate)>=minDrop&&num(x.pdp_sessions)>=minViews&&(!q||`${x.product_code} ${x.product_name}`.toLowerCase().includes(q)));const sorts={priority:(a,b)=>b._priority-a._priority||num(b.revenue)-num(a.revenue)||num(b.pdp_sessions)-num(a.pdp_sessions),revenue:(a,b)=>num(b.revenue)-num(a.revenue),views:(a,b)=>num(b.pdp_sessions)-num(a.pdp_sessions),drop:(a,b)=>num(b.pdp_abandonment_rate)-num(a.pdp_abandonment_rate),cvr:(a,b)=>num(a.cvr)-num(b.cvr)};list.sort(sorts[mode]);resultCount.textContent=`${fmt(list.length)}개 상품`;empty.classList.toggle('hidden',list.length>0);rows.innerHTML=list.slice(0,300).map((x,i)=>{const cls=x._priority>=85?'critical':x._priority>=70?'high':'';return `<tr><td><span class="rank">${i+1}</span></td><td><div class="font-black">${esc(x.product_name||'상품명 미수집')}</div><div class="code mt-1">${esc(x.product_code)}</div></td><td><span class="priority ${cls}">${x._priority}</span></td><td><b>${pct(x.pdp_abandonment_rate)}</b><div class="bar"><i style="width:${Math.min(100,num(x.pdp_abandonment_rate))}%"></i></div></td><td>${fmt(x.pdp_sessions)}</td><td>${fmt(x.add_to_cart_sessions)}</td><td>${fmt(x.purchase_sessions)}</td><td>${pct(x.cvr)}</td><td>${won(x.revenue)}</td></tr>`}).join('')}
[search,dropFilter,volumeFilter,sort].forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',render));async function boot(){try{const response=await fetch('./data.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);DATA=await response.json();ALL=Array.isArray(DATA.products)?DATA.products:[];const revs=ALL.map(x=>x.revenue),views=ALL.map(x=>x.pdp_sessions),drops=ALL.map(x=>x.pdp_abandonment_rate);ALL.forEach(x=>{const rp=percentile(revs,x.revenue),vp=percentile(views,x.pdp_sessions),dp=percentile(drops,x.pdp_abandonment_rate);x._priority=Math.round(100*(.4*Math.max(rp,vp)+.4*((rp+vp)/2)+.2*dp))});period.textContent=`${DATA.data_start||'-'} ~ ${DATA.data_end||'-'}`;updated.textContent=(DATA.generated_at||'-').replace('T',' ').slice(0,16);const sum=k=>ALL.reduce((a,x)=>a+num(x[k]),0),high=ALL.filter(x=>num(x.pdp_abandonment_rate)>=70);kpis.innerHTML=[['fa-eye','전체 PDP View',fmt(sum('pdp_sessions'))],['fa-arrow-right-from-bracket','고이탈 상품',fmt(high.length)+'개'],['fa-sack-dollar','고이탈 상품 매출',won(high.reduce((a,x)=>a+num(x.revenue),0))],['fa-cart-shopping','전체 PDP→장바구니',pct(sum('add_to_cart_sessions')/Math.max(sum('pdp_sessions'),1)*100)]].map(x=>`<article class="kpi glass"><div class="eyebrow"><i class="fa-solid ${x[0]} mr-2"></i>${x[1]}</div><div class="kpi-value">${x[2]}</div></article>`).join('');render()}catch(error){empty.classList.remove('hidden');empty.textContent='PDP 데이터를 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.';console.error(error)}}boot();
</script></body></html>'''


if __name__ == "__main__":
    raise SystemExit(main())
